import type { ActivityType } from "./index";

export const DEFAULT_ACTIVITY_TYPES: ActivityType[] = [
  { id: "1", user_id: "demo", name: "Left Home", category: "COMMUTE", is_paired: false, pair_label: null, is_expense_trigger: false, expense_reimbursable_rule: "NEVER", reimbursable_conditions: {}, icon: "🏠", color: "#64748B", sort_order: 1, active: true, created_at: new Date().toISOString() },
  { id: "2", user_id: "demo", name: "Reached Office", category: "COMMUTE", is_paired: false, pair_label: null, is_expense_trigger: false, expense_reimbursable_rule: "NEVER", reimbursable_conditions: {}, icon: "🏢", color: "#64748B", sort_order: 2, active: true, created_at: new Date().toISOString() },
  { id: "3", user_id: "demo", name: "Left Office", category: "COMMUTE", is_paired: false, pair_label: null, is_expense_trigger: false, expense_reimbursable_rule: "NEVER", reimbursable_conditions: {}, icon: "🚗", color: "#64748B", sort_order: 3, active: true, created_at: new Date().toISOString() },
  { id: "4", user_id: "demo", name: "Reached Home", category: "COMMUTE", is_paired: false, pair_label: null, is_expense_trigger: false, expense_reimbursable_rule: "NEVER", reimbursable_conditions: {}, icon: "🏠", color: "#64748B", sort_order: 4, active: true, created_at: new Date().toISOString() },
  { id: "5", user_id: "demo", name: "Left for Site", category: "COMMUTE", is_paired: false, pair_label: null, is_expense_trigger: true, expense_reimbursable_rule: "CONDITIONAL", reimbursable_conditions: { rule_type: "TRIP_TYPE_MATCH", allowed_trip_types: ["OFFICE_TO_SITE", "SITE_TO_SITE"] }, icon: "🚧", color: "#F59E0B", sort_order: 5, active: true, created_at: new Date().toISOString() },
  { id: "6", user_id: "demo", name: "Reached Site", category: "COMMUTE", is_paired: false, pair_label: null, is_expense_trigger: false, expense_reimbursable_rule: "NEVER", reimbursable_conditions: {}, icon: "🚧", color: "#F59E0B", sort_order: 6, active: true, created_at: new Date().toISOString() },
  { id: "7", user_id: "demo", name: "Left Site", category: "COMMUTE", is_paired: false, pair_label: null, is_expense_trigger: true, expense_reimbursable_rule: "CONDITIONAL", reimbursable_conditions: { rule_type: "TRIP_TYPE_MATCH", allowed_trip_types: ["SITE_TO_OFFICE", "SITE_TO_SITE"] }, icon: "🚧", color: "#F59E0B", sort_order: 7, active: true, created_at: new Date().toISOString() },
  { id: "8", user_id: "demo", name: "Work Started", category: "WORK", is_paired: true, pair_label: "Work Ended", is_expense_trigger: false, expense_reimbursable_rule: "NEVER", reimbursable_conditions: {}, icon: "💼", color: "#6366F1", sort_order: 8, active: true, created_at: new Date().toISOString() },
  { id: "9", user_id: "demo", name: "Tea Break Start", category: "BREAK", is_paired: true, pair_label: "Tea Break End", is_expense_trigger: false, expense_reimbursable_rule: "NEVER", reimbursable_conditions: {}, icon: "☕", color: "#92400E", sort_order: 9, active: true, created_at: new Date().toISOString() },
  { id: "10", user_id: "demo", name: "Lunch Start", category: "MEAL", is_paired: true, pair_label: "Lunch End", is_expense_trigger: true, expense_reimbursable_rule: "CONDITIONAL", reimbursable_conditions: { rule_type: "ACTIVE_TRIP_REIMBURSABLE" }, icon: "🍽️", color: "#10B981", sort_order: 10, active: true, created_at: new Date().toISOString() },
  { id: "11", user_id: "demo", name: "Dinner Start", category: "MEAL", is_paired: true, pair_label: "Dinner End", is_expense_trigger: true, expense_reimbursable_rule: "CONDITIONAL", reimbursable_conditions: { rule_type: "ACTIVE_TRIP_REIMBURSABLE" }, icon: "🍽️", color: "#10B981", sort_order: 11, active: true, created_at: new Date().toISOString() },
  { id: "12", user_id: "demo", name: "Went to Sleep", category: "SLEEP", is_paired: true, pair_label: "Woke Up", is_expense_trigger: false, expense_reimbursable_rule: "NEVER", reimbursable_conditions: {}, icon: "🌙", color: "#8B5CF6", sort_order: 12, active: true, created_at: new Date().toISOString() },
  { id: "13", user_id: "demo", name: "Reached Site (From Home)", category: "SITE_VISIT", is_paired: false, pair_label: null, is_expense_trigger: true, expense_reimbursable_rule: "CONDITIONAL", reimbursable_conditions: { rule_type: "TRIP_TYPE_MATCH", allowed_trip_types: ["HOME_TO_SITE", "OFFICE_TO_SITE"] }, icon: "🏗️", color: "#EF4444", sort_order: 13, active: true, created_at: new Date().toISOString() },
  { id: "14", user_id: "demo", name: "Hotel Check-In", category: "SITE_VISIT", is_paired: true, pair_label: "Hotel Check-Out", is_expense_trigger: true, expense_reimbursable_rule: "ALWAYS", reimbursable_conditions: {}, icon: "🏗️", color: "#EF4444", sort_order: 14, active: true, created_at: new Date().toISOString() },
  { id: "15", user_id: "demo", name: "Site Work Started", category: "SITE_VISIT", is_paired: true, pair_label: "Site Work Ended", is_expense_trigger: false, expense_reimbursable_rule: "NEVER", reimbursable_conditions: {}, icon: "🏗️", color: "#EF4444", sort_order: 15, active: true, created_at: new Date().toISOString() },
  { id: "16", user_id: "demo", name: "Left Site for Office", category: "SITE_VISIT", is_paired: false, pair_label: null, is_expense_trigger: true, expense_reimbursable_rule: "CONDITIONAL", reimbursable_conditions: { rule_type: "TRIP_TYPE_MATCH", allowed_trip_types: ["SITE_TO_OFFICE", "SITE_TO_SITE"] }, icon: "🏗️", color: "#EF4444", sort_order: 16, active: true, created_at: new Date().toISOString() },
  { id: "17", user_id: "demo", name: "Left Site for Home", category: "SITE_VISIT", is_paired: false, pair_label: null, is_expense_trigger: true, expense_reimbursable_rule: "CONDITIONAL", reimbursable_conditions: { rule_type: "TRIP_TYPE_MATCH", allowed_trip_types: ["SITE_TO_HOME", "SITE_TO_SITE"] }, icon: "🏗️", color: "#EF4444", sort_order: 17, active: true, created_at: new Date().toISOString() },
  { id: "18", user_id: "demo", name: "Gym Start", category: "PERSONAL", is_paired: true, pair_label: "Gym End", is_expense_trigger: false, expense_reimbursable_rule: "NEVER", reimbursable_conditions: {}, icon: "💪", color: "#06B6D4", sort_order: 18, active: true, created_at: new Date().toISOString() },
  { id: "19", user_id: "demo", name: "Prayer/Namaz Start", category: "PERSONAL", is_paired: true, pair_label: "Prayer/Namaz End", is_expense_trigger: false, expense_reimbursable_rule: "NEVER", reimbursable_conditions: {}, icon: "🕌", color: "#D97706", sort_order: 19, active: true, created_at: new Date().toISOString() },
  { id: "20", user_id: "demo", name: "Personal Errand Start", category: "PERSONAL", is_paired: true, pair_label: "Personal Errand End", is_expense_trigger: false, expense_reimbursable_rule: "NEVER", reimbursable_conditions: {}, icon: "🛒", color: "#6B7280", sort_order: 20, active: true, created_at: new Date().toISOString() },

  // End pairs
  { id: "101", user_id: "demo", name: "Work Ended", category: "WORK", is_paired: false, pair_label: null, is_expense_trigger: false, expense_reimbursable_rule: "NEVER", reimbursable_conditions: {}, icon: "💼", color: "#6366F1", sort_order: 101, active: true, created_at: new Date().toISOString() },
  { id: "102", user_id: "demo", name: "Tea Break End", category: "BREAK", is_paired: false, pair_label: null, is_expense_trigger: false, expense_reimbursable_rule: "NEVER", reimbursable_conditions: {}, icon: "☕", color: "#92400E", sort_order: 102, active: true, created_at: new Date().toISOString() },
  { id: "103", user_id: "demo", name: "Lunch End", category: "MEAL", is_paired: false, pair_label: null, is_expense_trigger: false, expense_reimbursable_rule: "NEVER", reimbursable_conditions: {}, icon: "🍽️", color: "#10B981", sort_order: 103, active: true, created_at: new Date().toISOString() },
  { id: "104", user_id: "demo", name: "Dinner End", category: "MEAL", is_paired: false, pair_label: null, is_expense_trigger: false, expense_reimbursable_rule: "NEVER", reimbursable_conditions: {}, icon: "🍽️", color: "#10B981", sort_order: 104, active: true, created_at: new Date().toISOString() },
  { id: "105", user_id: "demo", name: "Woke Up", category: "SLEEP", is_paired: false, pair_label: null, is_expense_trigger: false, expense_reimbursable_rule: "NEVER", reimbursable_conditions: {}, icon: "🌙", color: "#8B5CF6", sort_order: 105, active: true, created_at: new Date().toISOString() },
  { id: "106", user_id: "demo", name: "Hotel Check-Out", category: "SITE_VISIT", is_paired: false, pair_label: null, is_expense_trigger: false, expense_reimbursable_rule: "NEVER", reimbursable_conditions: {}, icon: "🏗️", color: "#EF4444", sort_order: 106, active: true, created_at: new Date().toISOString() },
  { id: "107", user_id: "demo", name: "Site Work Ended", category: "SITE_VISIT", is_paired: false, pair_label: null, is_expense_trigger: false, expense_reimbursable_rule: "NEVER", reimbursable_conditions: {}, icon: "🏗️", color: "#EF4444", sort_order: 107, active: true, created_at: new Date().toISOString() },
  { id: "108", user_id: "demo", name: "Gym End", category: "PERSONAL", is_paired: false, pair_label: null, is_expense_trigger: false, expense_reimbursable_rule: "NEVER", reimbursable_conditions: {}, icon: "💪", color: "#06B6D4", sort_order: 108, active: true, created_at: new Date().toISOString() },
  { id: "109", user_id: "demo", name: "Prayer/Namaz End", category: "PERSONAL", is_paired: false, pair_label: null, is_expense_trigger: false, expense_reimbursable_rule: "NEVER", reimbursable_conditions: {}, icon: "🕌", color: "#D97706", sort_order: 109, active: true, created_at: new Date().toISOString() },
  { id: "110", user_id: "demo", name: "Personal Errand End", category: "PERSONAL", is_paired: false, pair_label: null, is_expense_trigger: false, expense_reimbursable_rule: "NEVER", reimbursable_conditions: {}, icon: "🛒", color: "#6B7280", sort_order: 110, active: true, created_at: new Date().toISOString() }
];
